// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: advertisements_storage.proto

package avdertisement_storage

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_USER  UserRole = 0
	UserRole_USER_ROLE_ADMIN UserRole = 1
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_USER",
		1: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_USER":  0,
		"USER_ROLE_ADMIN": 1,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_advertisements_storage_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_advertisements_storage_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{0}
}

type Advertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        int64                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_advertisements_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Advertisement) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Advertisement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Advertisement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Advertisement) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Advertisement) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Advertisement) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Advertisement) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Advertisement) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId    int64                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdvertisementRequest) Reset() {
	*x = CreateAdvertisementRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertisementRequest) ProtoMessage() {}

func (x *CreateAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*CreateAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdvertisementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdvertisementRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdvertisementRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateAdvertisementRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAdvertisementRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *CreateAdvertisementRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateAdvertisementRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *Advertisement         `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdvertisementResponse) Reset() {
	*x = CreateAdvertisementResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdvertisementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertisementResponse) ProtoMessage() {}

func (x *CreateAdvertisementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertisementResponse.ProtoReflect.Descriptor instead.
func (*CreateAdvertisementResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdvertisementResponse) GetAdvertisement() *Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type GetAdvertisementByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvertisementByIdRequest) Reset() {
	*x = GetAdvertisementByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvertisementByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertisementByIdRequest) ProtoMessage() {}

func (x *GetAdvertisementByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertisementByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAdvertisementByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdvertisementByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAdvertisementByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *Advertisement         `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdvertisementByIdResponse) Reset() {
	*x = GetAdvertisementByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvertisementByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertisementByIdResponse) ProtoMessage() {}

func (x *GetAdvertisementByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertisementByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAdvertisementByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdvertisementByIdResponse) GetAdvertisement() *Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type GetAllAdvertisementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAdvertisementsRequest) Reset() {
	*x = GetAllAdvertisementsRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAdvertisementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAdvertisementsRequest) ProtoMessage() {}

func (x *GetAllAdvertisementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAdvertisementsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAdvertisementsRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{5}
}

type GetAllAdvertisementsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Advertisements []*Advertisement       `protobuf:"bytes,1,rep,name=advertisements,proto3" json:"advertisements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAllAdvertisementsResponse) Reset() {
	*x = GetAllAdvertisementsResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAdvertisementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAdvertisementsResponse) ProtoMessage() {}

func (x *GetAllAdvertisementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAdvertisementsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAdvertisementsResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllAdvertisementsResponse) GetAdvertisements() []*Advertisement {
	if x != nil {
		return x.Advertisements
	}
	return nil
}

type UpdateAdvertisementByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdvertisementByIdRequest) Reset() {
	*x = UpdateAdvertisementByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdvertisementByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertisementByIdRequest) ProtoMessage() {}

func (x *UpdateAdvertisementByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertisementByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdvertisementByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdvertisementByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAdvertisementByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *Advertisement         `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdvertisementByIdResponse) Reset() {
	*x = UpdateAdvertisementByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdvertisementByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertisementByIdResponse) ProtoMessage() {}

func (x *UpdateAdvertisementByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertisementByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdvertisementByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAdvertisementByIdResponse) GetAdvertisement() *Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type DeleteAdvertisementByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementByIDRequest) Reset() {
	*x = DeleteAdvertisementByIDRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdvertisementByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertisementByIDRequest) ProtoMessage() {}

func (x *DeleteAdvertisementByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertisementByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdvertisementByIDRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAdvertisementByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAdvertisementByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementByIDResponse) Reset() {
	*x = DeleteAdvertisementByIDResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdvertisementByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertisementByIDResponse) ProtoMessage() {}

func (x *DeleteAdvertisementByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertisementByIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdvertisementByIDResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{10}
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_advertisements_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{11}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdRequest) Reset() {
	*x = GetCategoryByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdRequest) ProtoMessage() {}

func (x *GetCategoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GetCategoryByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdResponse) Reset() {
	*x = GetCategoryByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdResponse) ProtoMessage() {}

func (x *GetCategoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GetCategoryByIdResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryByAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByAliasRequest) Reset() {
	*x = GetCategoryByAliasRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByAliasRequest) ProtoMessage() {}

func (x *GetCategoryByAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByAliasRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryByAliasRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategoryByAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetCategoryByAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByAliasResponse) Reset() {
	*x = GetCategoryByAliasResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByAliasResponse) ProtoMessage() {}

func (x *GetCategoryByAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByAliasResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryByAliasResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{17}
}

func (x *GetCategoryByAliasResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetAllCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesRequest) Reset() {
	*x = GetAllCategoriesRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesRequest) ProtoMessage() {}

func (x *GetAllCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{18}
}

type GetAllCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCategoriesResponse) Reset() {
	*x = GetAllCategoriesResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCategoriesResponse) ProtoMessage() {}

func (x *GetAllCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetAllCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type UpdateCategoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryByIdRequest) Reset() {
	*x = UpdateCategoryByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryByIdRequest) ProtoMessage() {}

func (x *UpdateCategoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCategoryByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCategoryByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryByIdResponse) Reset() {
	*x = UpdateCategoryByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryByIdResponse) ProtoMessage() {}

func (x *UpdateCategoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCategoryByIdResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryByIDRequest) Reset() {
	*x = DeleteCategoryByIDRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryByIDRequest) ProtoMessage() {}

func (x *DeleteCategoryByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryByIDRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCategoryByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCategoryByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryByIDResponse) Reset() {
	*x = DeleteCategoryByIDResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryByIDResponse) ProtoMessage() {}

func (x *DeleteCategoryByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryByIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryByIDResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{23}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          *UserRole              `protobuf:"varint,6,opt,name=role,proto3,enum=advertisements_storage.UserRole,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_advertisements_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{24}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return UserRole_USER_ROLE_USER
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          *UserRole              `protobuf:"varint,6,opt,name=role,proto3,enum=advertisements_storage.UserRole,oneof" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{25}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetRole() UserRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return UserRole_USER_ROLE_USER
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{26}
}

func (x *RegisterUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{27}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{28}
}

func (x *LoginUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{29}
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{30}
}

func (x *GetAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{32}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByIdRequest) Reset() {
	*x = UpdateUserByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByIdRequest) ProtoMessage() {}

func (x *UpdateUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateUserByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByIdResponse) Reset() {
	*x = UpdateUserByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByIdResponse) ProtoMessage() {}

func (x *UpdateUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByIdRequest) Reset() {
	*x = DeleteUserByIdRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByIdRequest) ProtoMessage() {}

func (x *DeleteUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteUserByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByIdResponse) Reset() {
	*x = DeleteUserByIdResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByIdResponse) ProtoMessage() {}

func (x *DeleteUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{36}
}

type SearchAdvertisementByTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAdvertisementByTitleRequest) Reset() {
	*x = SearchAdvertisementByTitleRequest{}
	mi := &file_advertisements_storage_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdvertisementByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdvertisementByTitleRequest) ProtoMessage() {}

func (x *SearchAdvertisementByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdvertisementByTitleRequest.ProtoReflect.Descriptor instead.
func (*SearchAdvertisementByTitleRequest) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{37}
}

func (x *SearchAdvertisementByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SearchAdvertisementByTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement []*Advertisement       `protobuf:"bytes,1,rep,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAdvertisementByTitleResponse) Reset() {
	*x = SearchAdvertisementByTitleResponse{}
	mi := &file_advertisements_storage_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAdvertisementByTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAdvertisementByTitleResponse) ProtoMessage() {}

func (x *SearchAdvertisementByTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advertisements_storage_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAdvertisementByTitleResponse.ProtoReflect.Descriptor instead.
func (*SearchAdvertisementByTitleResponse) Descriptor() ([]byte, []int) {
	return file_advertisements_storage_proto_rawDescGZIP(), []int{38}
}

func (x *SearchAdvertisementByTitleResponse) GetAdvertisement() []*Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

var File_advertisements_storage_proto protoreflect.FileDescriptor

const file_advertisements_storage_proto_rawDesc = "" +
	"\n" +
	"\x1cadvertisements_storage.proto\x12\x16advertisements_storage\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\rAdvertisement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\b \x01(\x03R\x06userId\"\xff\x01\n" +
	"\x1aCreateAdvertisementRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12=\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\"j\n" +
	"\x1bCreateAdvertisementResponse\x12K\n" +
	"\radvertisement\x18\x01 \x01(\v2%.advertisements_storage.AdvertisementR\radvertisement\"-\n" +
	"\x1bGetAdvertisementByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"k\n" +
	"\x1cGetAdvertisementByIdResponse\x12K\n" +
	"\radvertisement\x18\x01 \x01(\v2%.advertisements_storage.AdvertisementR\radvertisement\"\x1d\n" +
	"\x1bGetAllAdvertisementsRequest\"m\n" +
	"\x1cGetAllAdvertisementsResponse\x12M\n" +
	"\x0eadvertisements\x18\x01 \x03(\v2%.advertisements_storage.AdvertisementR\x0eadvertisements\"0\n" +
	"\x1eUpdateAdvertisementByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"n\n" +
	"\x1fUpdateAdvertisementByIdResponse\x12K\n" +
	"\radvertisement\x18\x01 \x01(\v2%.advertisements_storage.AdvertisementR\radvertisement\"0\n" +
	"\x1eDeleteAdvertisementByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x1fDeleteAdvertisementByIDResponse\"D\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"A\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"V\n" +
	"\x16CreateCategoryResponse\x12<\n" +
	"\bcategory\x18\x01 \x01(\v2 .advertisements_storage.CategoryR\bcategory\"(\n" +
	"\x16GetCategoryByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"W\n" +
	"\x17GetCategoryByIdResponse\x12<\n" +
	"\bcategory\x18\x01 \x01(\v2 .advertisements_storage.CategoryR\bcategory\"1\n" +
	"\x19GetCategoryByAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"Z\n" +
	"\x1aGetCategoryByAliasResponse\x12<\n" +
	"\bcategory\x18\x01 \x01(\v2 .advertisements_storage.CategoryR\bcategory\"\x19\n" +
	"\x17GetAllCategoriesRequest\"\\\n" +
	"\x18GetAllCategoriesResponse\x12@\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2 .advertisements_storage.CategoryR\n" +
	"categories\"+\n" +
	"\x19UpdateCategoryByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Z\n" +
	"\x1aUpdateCategoryByIdResponse\x12<\n" +
	"\bcategory\x18\x01 \x01(\v2 .advertisements_storage.CategoryR\bcategory\"+\n" +
	"\x19DeleteCategoryByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1c\n" +
	"\x1aDeleteCategoryByIDResponse\"\xd1\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x129\n" +
	"\x04role\x18\x06 \x01(\x0e2 .advertisements_storage.UserRoleH\x00R\x04role\x88\x01\x01B\a\n" +
	"\x05_role\"\xc7\x01\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x129\n" +
	"\x04role\x18\x06 \x01(\x0e2 .advertisements_storage.UserRoleH\x00R\x04role\x88\x01\x01B\a\n" +
	"\x05_role\"H\n" +
	"\x14RegisterUserResponse\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.advertisements_storage.UserR\x04user\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"6\n" +
	"\x11LoginUserResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x14\n" +
	"\x12GetAllUsersRequest\"I\n" +
	"\x13GetAllUsersResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.advertisements_storage.UserR\x05users\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x13GetUserByIdResponse\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.advertisements_storage.UserR\x04user\"'\n" +
	"\x15UpdateUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"J\n" +
	"\x16UpdateUserByIdResponse\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.advertisements_storage.UserR\x04user\"'\n" +
	"\x15DeleteUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x16DeleteUserByIdResponse\"9\n" +
	"!SearchAdvertisementByTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"q\n" +
	"\"SearchAdvertisementByTitleResponse\x12K\n" +
	"\radvertisement\x18\x01 \x03(\v2%.advertisements_storage.AdvertisementR\radvertisement*3\n" +
	"\bUserRole\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x012\xaa\x11\n" +
	"\x15AdvertisementsStorage\x12~\n" +
	"\x13CreateAdvertisement\x122.advertisements_storage.CreateAdvertisementRequest\x1a3.advertisements_storage.CreateAdvertisementResponse\x12\x81\x01\n" +
	"\x14GetAdvertisementById\x123.advertisements_storage.GetAdvertisementByIdRequest\x1a4.advertisements_storage.GetAdvertisementByIdResponse\x12\x81\x01\n" +
	"\x14GetAllAdvertisements\x123.advertisements_storage.GetAllAdvertisementsRequest\x1a4.advertisements_storage.GetAllAdvertisementsResponse\x12\x8a\x01\n" +
	"\x17UpdateAdvertisementById\x126.advertisements_storage.UpdateAdvertisementByIdRequest\x1a7.advertisements_storage.UpdateAdvertisementByIdResponse\x12\x8a\x01\n" +
	"\x17DeleteAdvertisementByID\x126.advertisements_storage.DeleteAdvertisementByIDRequest\x1a7.advertisements_storage.DeleteAdvertisementByIDResponse\x12o\n" +
	"\x0eCreateCategory\x12-.advertisements_storage.CreateCategoryRequest\x1a..advertisements_storage.CreateCategoryResponse\x12r\n" +
	"\x0fGetCategoryById\x12..advertisements_storage.GetCategoryByIdRequest\x1a/.advertisements_storage.GetCategoryByIdResponse\x12{\n" +
	"\x12GetCategoryByAlias\x121.advertisements_storage.GetCategoryByAliasRequest\x1a2.advertisements_storage.GetCategoryByAliasResponse\x12u\n" +
	"\x10GetAllCategories\x12/.advertisements_storage.GetAllCategoriesRequest\x1a0.advertisements_storage.GetAllCategoriesResponse\x12{\n" +
	"\x12UpdateCategoryById\x121.advertisements_storage.UpdateCategoryByIdRequest\x1a2.advertisements_storage.UpdateCategoryByIdResponse\x12{\n" +
	"\x12DeleteCategoryById\x121.advertisements_storage.DeleteCategoryByIDRequest\x1a2.advertisements_storage.DeleteCategoryByIDResponse\x12i\n" +
	"\fRegisterUser\x12+.advertisements_storage.RegisterUserRequest\x1a,.advertisements_storage.RegisterUserResponse\x12`\n" +
	"\tLoginUser\x12(.advertisements_storage.LoginUserRequest\x1a).advertisements_storage.LoginUserResponse\x12f\n" +
	"\vGetAllUsers\x12*.advertisements_storage.GetAllUsersRequest\x1a+.advertisements_storage.GetAllUsersResponse\x12f\n" +
	"\vGetUserByID\x12*.advertisements_storage.GetUserByIDRequest\x1a+.advertisements_storage.GetUserByIdResponse\x12o\n" +
	"\x0eUpdateUserById\x12-.advertisements_storage.UpdateUserByIdRequest\x1a..advertisements_storage.UpdateUserByIdResponse\x12x\n" +
	"\x0eDeleteUserById\x12-.advertisements_storage.DeleteUserByIdRequest\x1a7.advertisements_storage.DeleteAdvertisementByIDResponse\x12\x93\x01\n" +
	"\x1aSearchAdvertisementByTitle\x129.advertisements_storage.SearchAdvertisementByTitleRequest\x1a:.advertisements_storage.SearchAdvertisementByTitleResponseB Z\x1e./pkg/pb;avdertisement_storageb\x06proto3"

var (
	file_advertisements_storage_proto_rawDescOnce sync.Once
	file_advertisements_storage_proto_rawDescData []byte
)

func file_advertisements_storage_proto_rawDescGZIP() []byte {
	file_advertisements_storage_proto_rawDescOnce.Do(func() {
		file_advertisements_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advertisements_storage_proto_rawDesc), len(file_advertisements_storage_proto_rawDesc)))
	})
	return file_advertisements_storage_proto_rawDescData
}

var file_advertisements_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_advertisements_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_advertisements_storage_proto_goTypes = []any{
	(UserRole)(0),                              // 0: advertisements_storage.UserRole
	(*Advertisement)(nil),                      // 1: advertisements_storage.Advertisement
	(*CreateAdvertisementRequest)(nil),         // 2: advertisements_storage.CreateAdvertisementRequest
	(*CreateAdvertisementResponse)(nil),        // 3: advertisements_storage.CreateAdvertisementResponse
	(*GetAdvertisementByIdRequest)(nil),        // 4: advertisements_storage.GetAdvertisementByIdRequest
	(*GetAdvertisementByIdResponse)(nil),       // 5: advertisements_storage.GetAdvertisementByIdResponse
	(*GetAllAdvertisementsRequest)(nil),        // 6: advertisements_storage.GetAllAdvertisementsRequest
	(*GetAllAdvertisementsResponse)(nil),       // 7: advertisements_storage.GetAllAdvertisementsResponse
	(*UpdateAdvertisementByIdRequest)(nil),     // 8: advertisements_storage.UpdateAdvertisementByIdRequest
	(*UpdateAdvertisementByIdResponse)(nil),    // 9: advertisements_storage.UpdateAdvertisementByIdResponse
	(*DeleteAdvertisementByIDRequest)(nil),     // 10: advertisements_storage.DeleteAdvertisementByIDRequest
	(*DeleteAdvertisementByIDResponse)(nil),    // 11: advertisements_storage.DeleteAdvertisementByIDResponse
	(*Category)(nil),                           // 12: advertisements_storage.Category
	(*CreateCategoryRequest)(nil),              // 13: advertisements_storage.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),             // 14: advertisements_storage.CreateCategoryResponse
	(*GetCategoryByIdRequest)(nil),             // 15: advertisements_storage.GetCategoryByIdRequest
	(*GetCategoryByIdResponse)(nil),            // 16: advertisements_storage.GetCategoryByIdResponse
	(*GetCategoryByAliasRequest)(nil),          // 17: advertisements_storage.GetCategoryByAliasRequest
	(*GetCategoryByAliasResponse)(nil),         // 18: advertisements_storage.GetCategoryByAliasResponse
	(*GetAllCategoriesRequest)(nil),            // 19: advertisements_storage.GetAllCategoriesRequest
	(*GetAllCategoriesResponse)(nil),           // 20: advertisements_storage.GetAllCategoriesResponse
	(*UpdateCategoryByIdRequest)(nil),          // 21: advertisements_storage.UpdateCategoryByIdRequest
	(*UpdateCategoryByIdResponse)(nil),         // 22: advertisements_storage.UpdateCategoryByIdResponse
	(*DeleteCategoryByIDRequest)(nil),          // 23: advertisements_storage.DeleteCategoryByIDRequest
	(*DeleteCategoryByIDResponse)(nil),         // 24: advertisements_storage.DeleteCategoryByIDResponse
	(*User)(nil),                               // 25: advertisements_storage.User
	(*RegisterUserRequest)(nil),                // 26: advertisements_storage.RegisterUserRequest
	(*RegisterUserResponse)(nil),               // 27: advertisements_storage.RegisterUserResponse
	(*LoginUserRequest)(nil),                   // 28: advertisements_storage.LoginUserRequest
	(*LoginUserResponse)(nil),                  // 29: advertisements_storage.LoginUserResponse
	(*GetAllUsersRequest)(nil),                 // 30: advertisements_storage.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),                // 31: advertisements_storage.GetAllUsersResponse
	(*GetUserByIDRequest)(nil),                 // 32: advertisements_storage.GetUserByIDRequest
	(*GetUserByIdResponse)(nil),                // 33: advertisements_storage.GetUserByIdResponse
	(*UpdateUserByIdRequest)(nil),              // 34: advertisements_storage.UpdateUserByIdRequest
	(*UpdateUserByIdResponse)(nil),             // 35: advertisements_storage.UpdateUserByIdResponse
	(*DeleteUserByIdRequest)(nil),              // 36: advertisements_storage.DeleteUserByIdRequest
	(*DeleteUserByIdResponse)(nil),             // 37: advertisements_storage.DeleteUserByIdResponse
	(*SearchAdvertisementByTitleRequest)(nil),  // 38: advertisements_storage.SearchAdvertisementByTitleRequest
	(*SearchAdvertisementByTitleResponse)(nil), // 39: advertisements_storage.SearchAdvertisementByTitleResponse
	(*timestamppb.Timestamp)(nil),              // 40: google.protobuf.Timestamp
}
var file_advertisements_storage_proto_depIdxs = []int32{
	40, // 0: advertisements_storage.Advertisement.published_at:type_name -> google.protobuf.Timestamp
	40, // 1: advertisements_storage.CreateAdvertisementRequest.published_at:type_name -> google.protobuf.Timestamp
	1,  // 2: advertisements_storage.CreateAdvertisementResponse.advertisement:type_name -> advertisements_storage.Advertisement
	1,  // 3: advertisements_storage.GetAdvertisementByIdResponse.advertisement:type_name -> advertisements_storage.Advertisement
	1,  // 4: advertisements_storage.GetAllAdvertisementsResponse.advertisements:type_name -> advertisements_storage.Advertisement
	1,  // 5: advertisements_storage.UpdateAdvertisementByIdResponse.advertisement:type_name -> advertisements_storage.Advertisement
	12, // 6: advertisements_storage.CreateCategoryResponse.category:type_name -> advertisements_storage.Category
	12, // 7: advertisements_storage.GetCategoryByIdResponse.category:type_name -> advertisements_storage.Category
	12, // 8: advertisements_storage.GetCategoryByAliasResponse.category:type_name -> advertisements_storage.Category
	12, // 9: advertisements_storage.GetAllCategoriesResponse.categories:type_name -> advertisements_storage.Category
	12, // 10: advertisements_storage.UpdateCategoryByIdResponse.category:type_name -> advertisements_storage.Category
	0,  // 11: advertisements_storage.User.role:type_name -> advertisements_storage.UserRole
	0,  // 12: advertisements_storage.RegisterUserRequest.role:type_name -> advertisements_storage.UserRole
	25, // 13: advertisements_storage.RegisterUserResponse.user:type_name -> advertisements_storage.User
	25, // 14: advertisements_storage.GetAllUsersResponse.users:type_name -> advertisements_storage.User
	25, // 15: advertisements_storage.GetUserByIdResponse.user:type_name -> advertisements_storage.User
	25, // 16: advertisements_storage.UpdateUserByIdResponse.user:type_name -> advertisements_storage.User
	1,  // 17: advertisements_storage.SearchAdvertisementByTitleResponse.advertisement:type_name -> advertisements_storage.Advertisement
	2,  // 18: advertisements_storage.AdvertisementsStorage.CreateAdvertisement:input_type -> advertisements_storage.CreateAdvertisementRequest
	4,  // 19: advertisements_storage.AdvertisementsStorage.GetAdvertisementById:input_type -> advertisements_storage.GetAdvertisementByIdRequest
	6,  // 20: advertisements_storage.AdvertisementsStorage.GetAllAdvertisements:input_type -> advertisements_storage.GetAllAdvertisementsRequest
	8,  // 21: advertisements_storage.AdvertisementsStorage.UpdateAdvertisementById:input_type -> advertisements_storage.UpdateAdvertisementByIdRequest
	10, // 22: advertisements_storage.AdvertisementsStorage.DeleteAdvertisementByID:input_type -> advertisements_storage.DeleteAdvertisementByIDRequest
	13, // 23: advertisements_storage.AdvertisementsStorage.CreateCategory:input_type -> advertisements_storage.CreateCategoryRequest
	15, // 24: advertisements_storage.AdvertisementsStorage.GetCategoryById:input_type -> advertisements_storage.GetCategoryByIdRequest
	17, // 25: advertisements_storage.AdvertisementsStorage.GetCategoryByAlias:input_type -> advertisements_storage.GetCategoryByAliasRequest
	19, // 26: advertisements_storage.AdvertisementsStorage.GetAllCategories:input_type -> advertisements_storage.GetAllCategoriesRequest
	21, // 27: advertisements_storage.AdvertisementsStorage.UpdateCategoryById:input_type -> advertisements_storage.UpdateCategoryByIdRequest
	23, // 28: advertisements_storage.AdvertisementsStorage.DeleteCategoryById:input_type -> advertisements_storage.DeleteCategoryByIDRequest
	26, // 29: advertisements_storage.AdvertisementsStorage.RegisterUser:input_type -> advertisements_storage.RegisterUserRequest
	28, // 30: advertisements_storage.AdvertisementsStorage.LoginUser:input_type -> advertisements_storage.LoginUserRequest
	30, // 31: advertisements_storage.AdvertisementsStorage.GetAllUsers:input_type -> advertisements_storage.GetAllUsersRequest
	32, // 32: advertisements_storage.AdvertisementsStorage.GetUserByID:input_type -> advertisements_storage.GetUserByIDRequest
	34, // 33: advertisements_storage.AdvertisementsStorage.UpdateUserById:input_type -> advertisements_storage.UpdateUserByIdRequest
	36, // 34: advertisements_storage.AdvertisementsStorage.DeleteUserById:input_type -> advertisements_storage.DeleteUserByIdRequest
	38, // 35: advertisements_storage.AdvertisementsStorage.SearchAdvertisementByTitle:input_type -> advertisements_storage.SearchAdvertisementByTitleRequest
	3,  // 36: advertisements_storage.AdvertisementsStorage.CreateAdvertisement:output_type -> advertisements_storage.CreateAdvertisementResponse
	5,  // 37: advertisements_storage.AdvertisementsStorage.GetAdvertisementById:output_type -> advertisements_storage.GetAdvertisementByIdResponse
	7,  // 38: advertisements_storage.AdvertisementsStorage.GetAllAdvertisements:output_type -> advertisements_storage.GetAllAdvertisementsResponse
	9,  // 39: advertisements_storage.AdvertisementsStorage.UpdateAdvertisementById:output_type -> advertisements_storage.UpdateAdvertisementByIdResponse
	11, // 40: advertisements_storage.AdvertisementsStorage.DeleteAdvertisementByID:output_type -> advertisements_storage.DeleteAdvertisementByIDResponse
	14, // 41: advertisements_storage.AdvertisementsStorage.CreateCategory:output_type -> advertisements_storage.CreateCategoryResponse
	16, // 42: advertisements_storage.AdvertisementsStorage.GetCategoryById:output_type -> advertisements_storage.GetCategoryByIdResponse
	18, // 43: advertisements_storage.AdvertisementsStorage.GetCategoryByAlias:output_type -> advertisements_storage.GetCategoryByAliasResponse
	20, // 44: advertisements_storage.AdvertisementsStorage.GetAllCategories:output_type -> advertisements_storage.GetAllCategoriesResponse
	22, // 45: advertisements_storage.AdvertisementsStorage.UpdateCategoryById:output_type -> advertisements_storage.UpdateCategoryByIdResponse
	24, // 46: advertisements_storage.AdvertisementsStorage.DeleteCategoryById:output_type -> advertisements_storage.DeleteCategoryByIDResponse
	27, // 47: advertisements_storage.AdvertisementsStorage.RegisterUser:output_type -> advertisements_storage.RegisterUserResponse
	29, // 48: advertisements_storage.AdvertisementsStorage.LoginUser:output_type -> advertisements_storage.LoginUserResponse
	31, // 49: advertisements_storage.AdvertisementsStorage.GetAllUsers:output_type -> advertisements_storage.GetAllUsersResponse
	33, // 50: advertisements_storage.AdvertisementsStorage.GetUserByID:output_type -> advertisements_storage.GetUserByIdResponse
	35, // 51: advertisements_storage.AdvertisementsStorage.UpdateUserById:output_type -> advertisements_storage.UpdateUserByIdResponse
	11, // 52: advertisements_storage.AdvertisementsStorage.DeleteUserById:output_type -> advertisements_storage.DeleteAdvertisementByIDResponse
	39, // 53: advertisements_storage.AdvertisementsStorage.SearchAdvertisementByTitle:output_type -> advertisements_storage.SearchAdvertisementByTitleResponse
	36, // [36:54] is the sub-list for method output_type
	18, // [18:36] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_advertisements_storage_proto_init() }
func file_advertisements_storage_proto_init() {
	if File_advertisements_storage_proto != nil {
		return
	}
	file_advertisements_storage_proto_msgTypes[24].OneofWrappers = []any{}
	file_advertisements_storage_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advertisements_storage_proto_rawDesc), len(file_advertisements_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advertisements_storage_proto_goTypes,
		DependencyIndexes: file_advertisements_storage_proto_depIdxs,
		EnumInfos:         file_advertisements_storage_proto_enumTypes,
		MessageInfos:      file_advertisements_storage_proto_msgTypes,
	}.Build()
	File_advertisements_storage_proto = out.File
	file_advertisements_storage_proto_goTypes = nil
	file_advertisements_storage_proto_depIdxs = nil
}
