// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: advertisements_storage.proto

package avdertisement_storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdvertisementsStorage_CreateAdvertisement_FullMethodName        = "/advertisements_storage.AdvertisementsStorage/CreateAdvertisement"
	AdvertisementsStorage_GetAdvertisementById_FullMethodName       = "/advertisements_storage.AdvertisementsStorage/GetAdvertisementById"
	AdvertisementsStorage_GetAllAdvertisements_FullMethodName       = "/advertisements_storage.AdvertisementsStorage/GetAllAdvertisements"
	AdvertisementsStorage_UpdateAdvertisementById_FullMethodName    = "/advertisements_storage.AdvertisementsStorage/UpdateAdvertisementById"
	AdvertisementsStorage_DeleteAdvertisementByID_FullMethodName    = "/advertisements_storage.AdvertisementsStorage/DeleteAdvertisementByID"
	AdvertisementsStorage_CreateCategory_FullMethodName             = "/advertisements_storage.AdvertisementsStorage/CreateCategory"
	AdvertisementsStorage_GetCategoryById_FullMethodName            = "/advertisements_storage.AdvertisementsStorage/GetCategoryById"
	AdvertisementsStorage_GetCategoryByAlias_FullMethodName         = "/advertisements_storage.AdvertisementsStorage/GetCategoryByAlias"
	AdvertisementsStorage_GetAllCategories_FullMethodName           = "/advertisements_storage.AdvertisementsStorage/GetAllCategories"
	AdvertisementsStorage_UpdateCategoryById_FullMethodName         = "/advertisements_storage.AdvertisementsStorage/UpdateCategoryById"
	AdvertisementsStorage_DeleteCategoryById_FullMethodName         = "/advertisements_storage.AdvertisementsStorage/DeleteCategoryById"
	AdvertisementsStorage_RegisterUser_FullMethodName               = "/advertisements_storage.AdvertisementsStorage/RegisterUser"
	AdvertisementsStorage_LoginUser_FullMethodName                  = "/advertisements_storage.AdvertisementsStorage/LoginUser"
	AdvertisementsStorage_GetAllUsers_FullMethodName                = "/advertisements_storage.AdvertisementsStorage/GetAllUsers"
	AdvertisementsStorage_GetUserByID_FullMethodName                = "/advertisements_storage.AdvertisementsStorage/GetUserByID"
	AdvertisementsStorage_GetUserByEmail_FullMethodName             = "/advertisements_storage.AdvertisementsStorage/GetUserByEmail"
	AdvertisementsStorage_UpdateUserById_FullMethodName             = "/advertisements_storage.AdvertisementsStorage/UpdateUserById"
	AdvertisementsStorage_DeleteUserById_FullMethodName             = "/advertisements_storage.AdvertisementsStorage/DeleteUserById"
	AdvertisementsStorage_SearchAdvertisementByTitle_FullMethodName = "/advertisements_storage.AdvertisementsStorage/SearchAdvertisementByTitle"
)

// AdvertisementsStorageClient is the client API for AdvertisementsStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdvertisementsStorageClient interface {
	// Ads
	CreateAdvertisement(ctx context.Context, in *CreateAdvertisementRequest, opts ...grpc.CallOption) (*CreateAdvertisementResponse, error)
	GetAdvertisementById(ctx context.Context, in *GetAdvertisementByIdRequest, opts ...grpc.CallOption) (*GetAdvertisementByIdResponse, error)
	GetAllAdvertisements(ctx context.Context, in *GetAllAdvertisementsRequest, opts ...grpc.CallOption) (*GetAllAdvertisementsResponse, error)
	UpdateAdvertisementById(ctx context.Context, in *UpdateAdvertisementByIdRequest, opts ...grpc.CallOption) (*UpdateAdvertisementByIdResponse, error)
	DeleteAdvertisementByID(ctx context.Context, in *DeleteAdvertisementByIDRequest, opts ...grpc.CallOption) (*DeleteAdvertisementByIDResponse, error)
	// Categories
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	GetCategoryById(ctx context.Context, in *GetCategoryByIdRequest, opts ...grpc.CallOption) (*GetCategoryByIdResponse, error)
	GetCategoryByAlias(ctx context.Context, in *GetCategoryByAliasRequest, opts ...grpc.CallOption) (*GetCategoryByAliasResponse, error)
	GetAllCategories(ctx context.Context, in *GetAllCategoriesRequest, opts ...grpc.CallOption) (*GetAllCategoriesResponse, error)
	UpdateCategoryById(ctx context.Context, in *UpdateCategoryByIdRequest, opts ...grpc.CallOption) (*UpdateCategoryByIdResponse, error)
	DeleteCategoryById(ctx context.Context, in *DeleteCategoryByIDRequest, opts ...grpc.CallOption) (*DeleteCategoryByIDResponse, error)
	// Users
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error)
	UpdateUserById(ctx context.Context, in *UpdateUserByIdRequest, opts ...grpc.CallOption) (*UpdateUserByIdResponse, error)
	DeleteUserById(ctx context.Context, in *DeleteUserByIdRequest, opts ...grpc.CallOption) (*DeleteUserByIdResponse, error)
	// Search
	SearchAdvertisementByTitle(ctx context.Context, in *SearchAdvertisementByTitleRequest, opts ...grpc.CallOption) (*SearchAdvertisementByTitleResponse, error)
}

type advertisementsStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvertisementsStorageClient(cc grpc.ClientConnInterface) AdvertisementsStorageClient {
	return &advertisementsStorageClient{cc}
}

func (c *advertisementsStorageClient) CreateAdvertisement(ctx context.Context, in *CreateAdvertisementRequest, opts ...grpc.CallOption) (*CreateAdvertisementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdvertisementResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_CreateAdvertisement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetAdvertisementById(ctx context.Context, in *GetAdvertisementByIdRequest, opts ...grpc.CallOption) (*GetAdvertisementByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdvertisementByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetAdvertisementById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetAllAdvertisements(ctx context.Context, in *GetAllAdvertisementsRequest, opts ...grpc.CallOption) (*GetAllAdvertisementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAdvertisementsResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetAllAdvertisements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) UpdateAdvertisementById(ctx context.Context, in *UpdateAdvertisementByIdRequest, opts ...grpc.CallOption) (*UpdateAdvertisementByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdvertisementByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_UpdateAdvertisementById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) DeleteAdvertisementByID(ctx context.Context, in *DeleteAdvertisementByIDRequest, opts ...grpc.CallOption) (*DeleteAdvertisementByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdvertisementByIDResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_DeleteAdvertisementByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetCategoryById(ctx context.Context, in *GetCategoryByIdRequest, opts ...grpc.CallOption) (*GetCategoryByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetCategoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetCategoryByAlias(ctx context.Context, in *GetCategoryByAliasRequest, opts ...grpc.CallOption) (*GetCategoryByAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryByAliasResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetCategoryByAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetAllCategories(ctx context.Context, in *GetAllCategoriesRequest, opts ...grpc.CallOption) (*GetAllCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCategoriesResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetAllCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) UpdateCategoryById(ctx context.Context, in *UpdateCategoryByIdRequest, opts ...grpc.CallOption) (*UpdateCategoryByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_UpdateCategoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) DeleteCategoryById(ctx context.Context, in *DeleteCategoryByIDRequest, opts ...grpc.CallOption) (*DeleteCategoryByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryByIDResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_DeleteCategoryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUsersResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserByEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByEmailResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_GetUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) UpdateUserById(ctx context.Context, in *UpdateUserByIdRequest, opts ...grpc.CallOption) (*UpdateUserByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_UpdateUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) DeleteUserById(ctx context.Context, in *DeleteUserByIdRequest, opts ...grpc.CallOption) (*DeleteUserByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserByIdResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_DeleteUserById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementsStorageClient) SearchAdvertisementByTitle(ctx context.Context, in *SearchAdvertisementByTitleRequest, opts ...grpc.CallOption) (*SearchAdvertisementByTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAdvertisementByTitleResponse)
	err := c.cc.Invoke(ctx, AdvertisementsStorage_SearchAdvertisementByTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvertisementsStorageServer is the server API for AdvertisementsStorage service.
// All implementations should embed UnimplementedAdvertisementsStorageServer
// for forward compatibility.
type AdvertisementsStorageServer interface {
	// Ads
	CreateAdvertisement(context.Context, *CreateAdvertisementRequest) (*CreateAdvertisementResponse, error)
	GetAdvertisementById(context.Context, *GetAdvertisementByIdRequest) (*GetAdvertisementByIdResponse, error)
	GetAllAdvertisements(context.Context, *GetAllAdvertisementsRequest) (*GetAllAdvertisementsResponse, error)
	UpdateAdvertisementById(context.Context, *UpdateAdvertisementByIdRequest) (*UpdateAdvertisementByIdResponse, error)
	DeleteAdvertisementByID(context.Context, *DeleteAdvertisementByIDRequest) (*DeleteAdvertisementByIDResponse, error)
	// Categories
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	GetCategoryById(context.Context, *GetCategoryByIdRequest) (*GetCategoryByIdResponse, error)
	GetCategoryByAlias(context.Context, *GetCategoryByAliasRequest) (*GetCategoryByAliasResponse, error)
	GetAllCategories(context.Context, *GetAllCategoriesRequest) (*GetAllCategoriesResponse, error)
	UpdateCategoryById(context.Context, *UpdateCategoryByIdRequest) (*UpdateCategoryByIdResponse, error)
	DeleteCategoryById(context.Context, *DeleteCategoryByIDRequest) (*DeleteCategoryByIDResponse, error)
	// Users
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
	GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIdResponse, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error)
	UpdateUserById(context.Context, *UpdateUserByIdRequest) (*UpdateUserByIdResponse, error)
	DeleteUserById(context.Context, *DeleteUserByIdRequest) (*DeleteUserByIdResponse, error)
	// Search
	SearchAdvertisementByTitle(context.Context, *SearchAdvertisementByTitleRequest) (*SearchAdvertisementByTitleResponse, error)
}

// UnimplementedAdvertisementsStorageServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdvertisementsStorageServer struct{}

func (UnimplementedAdvertisementsStorageServer) CreateAdvertisement(context.Context, *CreateAdvertisementRequest) (*CreateAdvertisementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdvertisement not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetAdvertisementById(context.Context, *GetAdvertisementByIdRequest) (*GetAdvertisementByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdvertisementById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetAllAdvertisements(context.Context, *GetAllAdvertisementsRequest) (*GetAllAdvertisementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllAdvertisements not implemented")
}
func (UnimplementedAdvertisementsStorageServer) UpdateAdvertisementById(context.Context, *UpdateAdvertisementByIdRequest) (*UpdateAdvertisementByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdvertisementById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) DeleteAdvertisementByID(context.Context, *DeleteAdvertisementByIDRequest) (*DeleteAdvertisementByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdvertisementByID not implemented")
}
func (UnimplementedAdvertisementsStorageServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetCategoryById(context.Context, *GetCategoryByIdRequest) (*GetCategoryByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetCategoryByAlias(context.Context, *GetCategoryByAliasRequest) (*GetCategoryByAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryByAlias not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetAllCategories(context.Context, *GetAllCategoriesRequest) (*GetAllCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCategories not implemented")
}
func (UnimplementedAdvertisementsStorageServer) UpdateCategoryById(context.Context, *UpdateCategoryByIdRequest) (*UpdateCategoryByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategoryById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) DeleteCategoryById(context.Context, *DeleteCategoryByIDRequest) (*DeleteCategoryByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategoryById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedAdvertisementsStorageServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedAdvertisementsStorageServer) GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserByEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (UnimplementedAdvertisementsStorageServer) UpdateUserById(context.Context, *UpdateUserByIdRequest) (*UpdateUserByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) DeleteUserById(context.Context, *DeleteUserByIdRequest) (*DeleteUserByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserById not implemented")
}
func (UnimplementedAdvertisementsStorageServer) SearchAdvertisementByTitle(context.Context, *SearchAdvertisementByTitleRequest) (*SearchAdvertisementByTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAdvertisementByTitle not implemented")
}
func (UnimplementedAdvertisementsStorageServer) testEmbeddedByValue() {}

// UnsafeAdvertisementsStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdvertisementsStorageServer will
// result in compilation errors.
type UnsafeAdvertisementsStorageServer interface {
	mustEmbedUnimplementedAdvertisementsStorageServer()
}

func RegisterAdvertisementsStorageServer(s grpc.ServiceRegistrar, srv AdvertisementsStorageServer) {
	// If the following call panics, it indicates UnimplementedAdvertisementsStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdvertisementsStorage_ServiceDesc, srv)
}

func _AdvertisementsStorage_CreateAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).CreateAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_CreateAdvertisement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).CreateAdvertisement(ctx, req.(*CreateAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetAdvertisementById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdvertisementByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetAdvertisementById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetAdvertisementById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetAdvertisementById(ctx, req.(*GetAdvertisementByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetAllAdvertisements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAdvertisementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetAllAdvertisements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetAllAdvertisements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetAllAdvertisements(ctx, req.(*GetAllAdvertisementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_UpdateAdvertisementById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdvertisementByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).UpdateAdvertisementById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_UpdateAdvertisementById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).UpdateAdvertisementById(ctx, req.(*UpdateAdvertisementByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_DeleteAdvertisementByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdvertisementByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).DeleteAdvertisementByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_DeleteAdvertisementByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).DeleteAdvertisementByID(ctx, req.(*DeleteAdvertisementByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetCategoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetCategoryById(ctx, req.(*GetCategoryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetCategoryByAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryByAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetCategoryByAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetCategoryByAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetCategoryByAlias(ctx, req.(*GetCategoryByAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetAllCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetAllCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetAllCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetAllCategories(ctx, req.(*GetAllCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_UpdateCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).UpdateCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_UpdateCategoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).UpdateCategoryById(ctx, req.(*UpdateCategoryByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_DeleteCategoryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).DeleteCategoryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_DeleteCategoryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).DeleteCategoryById(ctx, req.(*DeleteCategoryByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetUserByID(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_GetUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_UpdateUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).UpdateUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_UpdateUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).UpdateUserById(ctx, req.(*UpdateUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_DeleteUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).DeleteUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_DeleteUserById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).DeleteUserById(ctx, req.(*DeleteUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementsStorage_SearchAdvertisementByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAdvertisementByTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementsStorageServer).SearchAdvertisementByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvertisementsStorage_SearchAdvertisementByTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementsStorageServer).SearchAdvertisementByTitle(ctx, req.(*SearchAdvertisementByTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdvertisementsStorage_ServiceDesc is the grpc.ServiceDesc for AdvertisementsStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdvertisementsStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "advertisements_storage.AdvertisementsStorage",
	HandlerType: (*AdvertisementsStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdvertisement",
			Handler:    _AdvertisementsStorage_CreateAdvertisement_Handler,
		},
		{
			MethodName: "GetAdvertisementById",
			Handler:    _AdvertisementsStorage_GetAdvertisementById_Handler,
		},
		{
			MethodName: "GetAllAdvertisements",
			Handler:    _AdvertisementsStorage_GetAllAdvertisements_Handler,
		},
		{
			MethodName: "UpdateAdvertisementById",
			Handler:    _AdvertisementsStorage_UpdateAdvertisementById_Handler,
		},
		{
			MethodName: "DeleteAdvertisementByID",
			Handler:    _AdvertisementsStorage_DeleteAdvertisementByID_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _AdvertisementsStorage_CreateCategory_Handler,
		},
		{
			MethodName: "GetCategoryById",
			Handler:    _AdvertisementsStorage_GetCategoryById_Handler,
		},
		{
			MethodName: "GetCategoryByAlias",
			Handler:    _AdvertisementsStorage_GetCategoryByAlias_Handler,
		},
		{
			MethodName: "GetAllCategories",
			Handler:    _AdvertisementsStorage_GetAllCategories_Handler,
		},
		{
			MethodName: "UpdateCategoryById",
			Handler:    _AdvertisementsStorage_UpdateCategoryById_Handler,
		},
		{
			MethodName: "DeleteCategoryById",
			Handler:    _AdvertisementsStorage_DeleteCategoryById_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _AdvertisementsStorage_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AdvertisementsStorage_LoginUser_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _AdvertisementsStorage_GetAllUsers_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _AdvertisementsStorage_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _AdvertisementsStorage_GetUserByEmail_Handler,
		},
		{
			MethodName: "UpdateUserById",
			Handler:    _AdvertisementsStorage_UpdateUserById_Handler,
		},
		{
			MethodName: "DeleteUserById",
			Handler:    _AdvertisementsStorage_DeleteUserById_Handler,
		},
		{
			MethodName: "SearchAdvertisementByTitle",
			Handler:    _AdvertisementsStorage_SearchAdvertisementByTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advertisements_storage.proto",
}
